###
#
# @file make.inc.mac
#
#  PLASMA is a software package provided by Univ. of Tennessee,
#  Univ. of California Berkeley and Univ. of Colorado Denver
#
# @version 2.6.0
# @author Julie Langou
# @author Mathieu Faverge
# @date 2010-11-15
#
###
#
# OS:       Mac OS X
# Compiler: GCC
# BLAS:     vecLib
#
###

# PLASMA install directory (./install by default)
#prefix      = /path/to/install/directory

# Compilers, linker/loader, archiver, options
CC          = gcc
FC          = gfortran
LOADER      = $(FC)

ARCH        = ar
ARCHFLAGS   = cr
RANLIB      = ranlib

CFLAGS      = -O2 -DADD_  -I/usr/include/malloc/
FFLAGS      = -O2
LDFLAGS     =

# Enable/Disable F90 compilation
PLASMA_F90 = 0

# BLAS library
LIBBLAS     = -framework vecLib

# CBLAS library
LIBCBLAS    = -L/path/to/cblas/lib/ -lcblas

# LAPACK and TMG library (LAPACK is included in vecLib)
LIBLAPACK   = -L/path/to/lapack_acml/lib/ -ltmg

# LAPACK C Wrapper library
INCCLAPACK  = -I/path/to/lapacke/include
LIBCLAPACK  = -L/path/to/lapacke/lib -llapacke
