###
#
# @file Makefile.internal
#
#  PLASMA is a software package provided by Univ. of Tennessee,
#  Univ. of California Berkeley and Univ. of Colorado Denver
#
# This file set all the common variables used by all Makefile of
# the project thanks to make.inc
#
# @version 2.6.0
# @author Mathieu Faverge
# @date 2010-11-15
#
###

include $(PLASMA_DIR)/make.inc
-include $(PLASMA_DIR)/make.inc.${MACHINE}

prefix ?= ./install

#///// D /// O ////// N /// O /// T ////// T /// O /// U /// C /// H /////
QUARKDIR ?= $(PLASMA_DIR)/quark
INCQUARK  = -I$(QUARKDIR)
LIBQUARK  = -L$(QUARKDIR) -lquark

# Include directories
INC         = -I$(PLASMA_DIR)/include $(INCQUARK)
INCEXT      = $(INCCLAPACK)

# Location of the libraries.
LIBDIR      = -L$(PLASMA_DIR)/lib

# Location and name of the PLASMA library.
LIBCOREBLAS     = $(PLASMA_DIR)/lib/libcoreblas.a
LIBCOREBLASQW   = $(PLASMA_DIR)/lib/libcoreblasqw.a
LIBCOREBLASRW   = $(PLASMA_DIR)/lib/libcoreblasrw.a
LIBRUNTIME	= $(PLASMA_DIR)/lib/libruntime.a
LIBPLASMA       = $(PLASMA_DIR)/lib/libplasma.a
LIBEZT_COREBLAS = $(PLASMA_DIR)/lib/libeztrace-coreblas.a
LIBEZT_CONVERT  = $(PLASMA_DIR)/lib/libeztrace-convert-coreblas.so

#             Trace librairies
# (we guess that all librairies have been installed
#     in the same directory by the installer)
EZT_DIR ?= /usr
GTG_DIR ?= $(EZT_DIR)
FXT_DIR ?= $(EZT_DIR)

ifeq (${PLASMA_TRACE}, 1)
        LIBTRACE = -L${EZT_DIR}/lib -leztrace -leztrace-coreblas -L$(FXT_DIR)/lib -lfxt
        CFLAGS += -DPLASMA_EZTRACE -I${EZT_DIR}/include
endif

#  All internal libraries
ifeq (1, $(words $(findstring CUDA, $(CFLAGS))))
LIB    = $(LIBDIR) -lplasma ${LIBTRACE} -lcoreblasqw -lcoreblasrw -lruntime -lcoreblasrw -lcoreblas -lplasma $(LIBQUARK)
else
LIB    = $(LIBDIR) -lplasma ${LIBTRACE} -lcoreblasqw -lruntime -lcoreblas -lplasma $(LIBQUARK)
endif

#  All external libraries
LIBEXT = $(LIBCBLAS) $(LIBCLAPACK) $(LIBLAPACK) $(LIBBLAS) -lpthread -lm

# Use Hwloc
HWLOC = $(shell pkg-config --libs hwloc 2> /dev/null )
ifeq (1, $(words $(findstring hwloc, $(HWLOC))))
        CFLAGS  := $(CFLAGS) -DPLASMA_HWLOC -DQUARK_HWLOC
        INCEXT  := $(INCEXT) $(shell pkg-config --cflags-only-I hwloc)
        LIBEXT  := $(LIBEXT) $(shell pkg-config --libs hwloc)
        require := hwloc
endif

GPU_TARGET      ?= Kepler
#
# NVCC options for the different cards
# First, add smXX for architecture names
#
ifneq ($(findstring Tesla, $(GPU_TARGET)),)
    # sm10 is no longer supported by CUDA 6.x nvcc
    GPU_TARGET += sm13
endif
ifneq ($(findstring Fermi, $(GPU_TARGET)),)
    GPU_TARGET += sm20
endif
ifneq ($(findstring Kepler, $(GPU_TARGET)),)
    GPU_TARGET += sm30 sm35
endif

#
# Next, add compile options for specific smXX
# sm_xx is binary, compute_xx is PTX for forward compatability
# MIN_ARCH is lowest requested version 
# NV_SM    accumulates sm_xx for all requested versions
# NV_COMP  is compute_xx for highest requested version
#
# See also $(info compile for ...) in Makefile
#
NV_SM    :=
NV_COMP  :=

ifneq ($(findstring sm10, $(GPU_TARGET)),)
    # sm10 is no longer supported by CUDA 6.x nvcc
    MIN_ARCH ?= 100
    NV_SM    += -gencode arch=compute_10,code=sm_10
    NV_COMP  := -gencode arch=compute_10,code=compute_10
endif
ifneq ($(findstring sm13, $(GPU_TARGET)),)
    MIN_ARCH ?= 130
    NV_SM    += -gencode arch=compute_13,code=sm_13
    NV_COMP  := -gencode arch=compute_13,code=compute_13
endif
ifneq ($(findstring sm20, $(GPU_TARGET)),)
    MIN_ARCH ?= 200
    NV_SM    += -gencode arch=compute_20,code=sm_20
    NV_COMP  := -gencode arch=compute_20,code=compute_20
endif
ifneq ($(findstring sm30, $(GPU_TARGET)),)
    MIN_ARCH ?= 300
    NV_SM    += -gencode arch=compute_30,code=sm_30
    NV_COMP  := -gencode arch=compute_30,code=compute_30
endif
ifneq ($(findstring sm35, $(GPU_TARGET)),)
    MIN_ARCH ?= 350
    NV_SM    += -gencode arch=compute_35,code=sm_35
    NV_COMP  := -gencode arch=compute_35,code=compute_35
endif
ifeq ($(NV_COMP),)
    $(error GPU_TARGET, currently $(GPU_TARGET), must contain one or more of Tesla, Fermi, Kepler, or sm{10,13,20,30,35}. Please edit your make.inc file)
endif
NVCCFLAGS += $(NV_SM) $(NV_COMP)

INC := $(INC) $(INCEXT)
LIB := $(LIB) $(LIBEXT)

#//////////////////////////////////////////////////////////////////////////

-include $(PLASMA_DIR)/Makefile.gen
