/**
 *
 * @file qwrapper_c.c
 *
 *  PLASMA core_blas tracing kernel
 *  PLASMA is a software package provided by Univ. of Tennessee,
 *  Univ. of California Berkeley and Univ. of Colorado Denver
 *
 *  This file provides the wrapper for each function of the
 *  core_blas library which will generate an event before and
 *  after the execution of the kernel.
 *  This file is automatically generated with convert2eztrace.pl
 *  script. DO NOT MANUALLY EDIT THIS FILE.
 *
 * @version 2.6.0
 * @author Mathieu Faverge
 * @date 2010-11-15
 * @generated c Tue Jan  7 11:45:26 2014
 *
 **/
#include <eztrace.h>
#include <ev_codes.h>
#include "common.h"
#include "coreblas_ev_codes.h"
#include "coreblas_macros.h"
#undef REAL
#define COMPLEX
FUNCTION_QUARK( CORE_scasum_quark, ASUM )
FUNCTION_QUARK( CORE_scasum_f1_quark, ASUM )
FUNCTION_QUARK( CORE_cbrdalg1_quark, BRDALG )
FUNCTION_QUARK( CORE_cgeadd_quark, GEADD )
FUNCTION_QUARK( CORE_cgelqt_quark, GELQT )
FUNCTION_QUARK( CORE_cgemm_quark, GEMM )
FUNCTION_QUARK( CORE_cgemm_f2_quark, GEMM )
FUNCTION_QUARK( CORE_cgemm_p2_quark, GEMM )
FUNCTION_QUARK( CORE_cgemm_p3_quark, GEMM )
FUNCTION_QUARK( CORE_cgemm_p2f1_quark, GEMM )
FUNCTION_QUARK( CORE_cgemm_tile_quark, GEMM )
FUNCTION_QUARK( CORE_cgemv_quark, GEMV )
FUNCTION_QUARK( CORE_cgemv_tile_quark, GEMV )
FUNCTION_QUARK( CORE_cgeqp3_init_quark, GEQP3_INIT )
FUNCTION_QUARK( CORE_cgeqp3_larfg_quark, LARFG )
FUNCTION_QUARK( CORE_cgeqp3_norms_quark, GEQP3_NORMS )
FUNCTION_QUARK( CORE_cgeqp3_pivot_quark, GEQP3_PIVOT )
FUNCTION_QUARK( CORE_cgeqp3_tntpiv_quark, GEQRT )
FUNCTION_QUARK( CORE_cgeqp3_update_quark, GEQP3_UPDATE )
FUNCTION_QUARK( CORE_cgeqrt_quark, GEQRT )
FUNCTION_QUARK( CORE_cgessm_quark, GESSM )
FUNCTION_QUARK( CORE_cgessq_quark, LASSQ )
FUNCTION_QUARK( CORE_cgessq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_cgetrf_quark, GETRF )
FUNCTION_QUARK( CORE_cgetrf_incpiv_quark, GETRF )
FUNCTION_QUARK( CORE_cgetrf_nopiv_quark, GETRF )
FUNCTION_QUARK( CORE_cgetrf_reclap_quark, GETRF )
FUNCTION_QUARK( CORE_cgetrf_rectil_quark, GETRF )
FUNCTION_QUARK( CORE_cgetrip_quark, GETRIP )
FUNCTION_QUARK( CORE_cgetrip_f1_quark, GETRIP )
FUNCTION_QUARK( CORE_cgetrip_f2_quark, GETRIP )
FUNCTION_QUARK( CORE_chegst_quark, HEGST )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_chemm_quark, HEMM )
#endif
#ifdef COMPLEX
FUNCTION_QUARK( CORE_cher2k_quark, HER2K )
#endif
FUNCTION_QUARK( CORE_cherfb_quark, HERFB )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_cherk_quark, HERK )
#endif
#ifdef COMPLEX
FUNCTION_QUARK( CORE_chessq_quark, LASSQ )
FUNCTION_QUARK( CORE_chessq_f1_quark, LASSQ )
#endif
FUNCTION_QUARK( CORE_clacpy_quark, LACPY )
FUNCTION_QUARK( CORE_clacpy_f1_quark, LACPY )
FUNCTION_QUARK( CORE_clacpy_pivot_quark, LACPY )
FUNCTION_QUARK( CORE_clange_quark, LANGE )
FUNCTION_QUARK( CORE_clange_f1_quark, LANGE )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_clanhe_quark, LANHE )
FUNCTION_QUARK( CORE_clanhe_f1_quark, LANHE )
#endif
FUNCTION_QUARK( CORE_clansy_quark, LANSY )
FUNCTION_QUARK( CORE_clansy_f1_quark, LANSY )
FUNCTION_QUARK( CORE_clantr_quark, LANGE )
FUNCTION_QUARK( CORE_clantr_f1_quark, LANGE )
FUNCTION_QUARK( CORE_claset2_quark, LASET )
FUNCTION_QUARK( CORE_claset_quark, LASET )
FUNCTION_QUARK( CORE_claswp_quark, LASWP )
FUNCTION_QUARK( CORE_claswp_f2_quark, LASWP )
FUNCTION_QUARK( CORE_claswp_ontile_quark, LASWP )
FUNCTION_QUARK( CORE_claswp_ontile_f2_quark, LASWP )
FUNCTION_QUARK( CORE_cswptr_ontile_quark, TRSM )
FUNCTION_QUARK( CORE_claswpc_ontile_quark, LASWP )
FUNCTION_QUARK( CORE_clatro_quark, LATRO )
FUNCTION_QUARK( CORE_clatro_f1_quark, LATRO )
FUNCTION_QUARK( CORE_clauum_quark, LAUUM )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_cplghe_quark, PLGHE )
#endif
FUNCTION_QUARK( CORE_cplgsy_quark, PLGSY )
FUNCTION_QUARK( CORE_cplrnt_quark, PLRNT )
FUNCTION_QUARK( CORE_cplssq_quark, LASSQ )
FUNCTION_QUARK( CORE_cpltmg_quark, PLRNT )
FUNCTION_QUARK( CORE_cpltmg_chebvand_quark, PLRNT )
FUNCTION_QUARK( CORE_cpltmg_circul_quark, PLRNT )
FUNCTION_QUARK( CORE_cpltmg_fiedler_quark, PLRNT )
FUNCTION_QUARK( CORE_cpltmg_hankel_quark, PLRNT )
FUNCTION_QUARK( CORE_cpltmg_toeppd1_quark, PLRNT )
FUNCTION_QUARK( CORE_cpltmg_toeppd2_quark, PLRNT )
FUNCTION_QUARK( CORE_cpotrf_quark, POTRF )
FUNCTION_QUARK( CORE_csetvar_quark, SETVAR )
FUNCTION_QUARK( CORE_cshiftw_quark, SHIFTW )
FUNCTION_QUARK( CORE_cshift_quark, SHIFT )
FUNCTION_QUARK( CORE_cssssm_quark, SSSSM )
FUNCTION_QUARK( CORE_cswpab_quark, SWPAB )
FUNCTION_QUARK( CORE_csymm_quark, SYMM )
FUNCTION_QUARK( CORE_csyr2k_quark, SYR2K )
FUNCTION_QUARK( CORE_csyrk_quark, SYRK )
FUNCTION_QUARK( CORE_csyssq_quark, LASSQ )
FUNCTION_QUARK( CORE_csyssq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_ctrasm_quark, ASUM )
FUNCTION_QUARK( CORE_ctrasm_f1_quark, ASUM )
FUNCTION_QUARK( CORE_ctrdalg1_quark, TRDALG )
FUNCTION_QUARK( CORE_ctrmm_quark, TRMM )
FUNCTION_QUARK( CORE_ctrmm_p2_quark, TRMM )
FUNCTION_QUARK( CORE_ctrsm_quark, TRSM )
FUNCTION_QUARK( CORE_ctrssq_quark, LASSQ )
FUNCTION_QUARK( CORE_ctrssq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_ctrtri_quark, TRTRI )
FUNCTION_QUARK( CORE_ctslqt_quark, TSLQT )
FUNCTION_QUARK( CORE_ctsmlq_quark, TSMLQ )
FUNCTION_QUARK( CORE_ctsmlq_corner_quark, TSMLQ )
FUNCTION_QUARK( CORE_ctsmlq_hetra1_quark, TSMLQ )
FUNCTION_QUARK( CORE_ctsmqr_quark, TSMQR )
FUNCTION_QUARK( CORE_ctsmqr_corner_quark, TSMQR )
FUNCTION_QUARK( CORE_ctsmqr_hetra1_quark, TSMQR )
FUNCTION_QUARK( CORE_ctsqrt_quark, TSQRT )
FUNCTION_QUARK( CORE_ctstrf_quark, TSTRF )
FUNCTION_QUARK( CORE_cttlqt_quark, TTLQT )
FUNCTION_QUARK( CORE_cttmlq_quark, TTMLQ )
FUNCTION_QUARK( CORE_cttmqr_quark, TTMQR )
FUNCTION_QUARK( CORE_cttqrt_quark, TTQRT )
FUNCTION_QUARK( CORE_cunmlq_quark, UNMLQ )
FUNCTION_QUARK( CORE_cunmqr_quark, UNMQR )

