/**
 *
 * @file qwrapper_d.c
 *
 *  PLASMA core_blas tracing kernel
 *  PLASMA is a software package provided by Univ. of Tennessee,
 *  Univ. of California Berkeley and Univ. of Colorado Denver
 *
 *  This file provides the wrapper for each function of the
 *  core_blas library which will generate an event before and
 *  after the execution of the kernel.
 *  This file is automatically generated with convert2eztrace.pl
 *  script. DO NOT MANUALLY EDIT THIS FILE.
 *
 * @version 2.6.0
 * @author Mathieu Faverge
 * @date 2010-11-15
 * @generated d Tue Jan  7 11:45:26 2014
 *
 **/
#include <eztrace.h>
#include <ev_codes.h>
#include "common.h"
#include "coreblas_ev_codes.h"
#include "coreblas_macros.h"
#undef COMPLEX
#define REAL
FUNCTION_QUARK( CORE_dasum_quark, ASUM )
FUNCTION_QUARK( CORE_dasum_f1_quark, ASUM )
FUNCTION_QUARK( CORE_dbrdalg1_quark, BRDALG )
FUNCTION_QUARK( CORE_dgeadd_quark, GEADD )
FUNCTION_QUARK( CORE_dgelqt_quark, GELQT )
FUNCTION_QUARK( CORE_dgemm_quark, GEMM )
FUNCTION_QUARK( CORE_dgemm_f2_quark, GEMM )
FUNCTION_QUARK( CORE_dgemm_p2_quark, GEMM )
FUNCTION_QUARK( CORE_dgemm_p3_quark, GEMM )
FUNCTION_QUARK( CORE_dgemm_p2f1_quark, GEMM )
FUNCTION_QUARK( CORE_dgemm_tile_quark, GEMM )
FUNCTION_QUARK( CORE_dgemv_quark, GEMV )
FUNCTION_QUARK( CORE_dgemv_tile_quark, GEMV )
FUNCTION_QUARK( CORE_dgeqp3_init_quark, GEQP3_INIT )
FUNCTION_QUARK( CORE_dgeqp3_larfg_quark, LARFG )
FUNCTION_QUARK( CORE_dgeqp3_norms_quark, GEQP3_NORMS )
FUNCTION_QUARK( CORE_dgeqp3_pivot_quark, GEQP3_PIVOT )
FUNCTION_QUARK( CORE_dgeqp3_tntpiv_quark, GEQRT )
FUNCTION_QUARK( CORE_dgeqp3_update_quark, GEQP3_UPDATE )
FUNCTION_QUARK( CORE_dgeqrt_quark, GEQRT )
FUNCTION_QUARK( CORE_dgessm_quark, GESSM )
FUNCTION_QUARK( CORE_dgessq_quark, LASSQ )
FUNCTION_QUARK( CORE_dgessq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_dgetrf_quark, GETRF )
FUNCTION_QUARK( CORE_dgetrf_incpiv_quark, GETRF )
FUNCTION_QUARK( CORE_dgetrf_nopiv_quark, GETRF )
FUNCTION_QUARK( CORE_dgetrf_reclap_quark, GETRF )
FUNCTION_QUARK( CORE_dgetrf_rectil_quark, GETRF )
FUNCTION_QUARK( CORE_dgetrip_quark, GETRIP )
FUNCTION_QUARK( CORE_dgetrip_f1_quark, GETRIP )
FUNCTION_QUARK( CORE_dgetrip_f2_quark, GETRIP )
FUNCTION_QUARK( CORE_dsygst_quark, HEGST )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_dsymm_quark, HEMM )
#endif
#ifdef COMPLEX
FUNCTION_QUARK( CORE_dsyr2k_quark, HER2K )
#endif
FUNCTION_QUARK( CORE_dsyrfb_quark, HERFB )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_dsyrk_quark, HERK )
#endif
#ifdef COMPLEX
FUNCTION_QUARK( CORE_dhessq_quark, LASSQ )
FUNCTION_QUARK( CORE_dhessq_f1_quark, LASSQ )
#endif
FUNCTION_QUARK( CORE_dlacpy_quark, LACPY )
FUNCTION_QUARK( CORE_dlacpy_f1_quark, LACPY )
FUNCTION_QUARK( CORE_dlacpy_pivot_quark, LACPY )
FUNCTION_QUARK( CORE_dlange_quark, LANGE )
FUNCTION_QUARK( CORE_dlange_f1_quark, LANGE )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_dlansy_quark, LANHE )
FUNCTION_QUARK( CORE_dlansy_f1_quark, LANHE )
#endif
FUNCTION_QUARK( CORE_dlansy_quark, LANSY )
FUNCTION_QUARK( CORE_dlansy_f1_quark, LANSY )
FUNCTION_QUARK( CORE_dlantr_quark, LANGE )
FUNCTION_QUARK( CORE_dlantr_f1_quark, LANGE )
FUNCTION_QUARK( CORE_dlaset2_quark, LASET )
FUNCTION_QUARK( CORE_dlaset_quark, LASET )
FUNCTION_QUARK( CORE_dlaswp_quark, LASWP )
FUNCTION_QUARK( CORE_dlaswp_f2_quark, LASWP )
FUNCTION_QUARK( CORE_dlaswp_ontile_quark, LASWP )
FUNCTION_QUARK( CORE_dlaswp_ontile_f2_quark, LASWP )
FUNCTION_QUARK( CORE_dswptr_ontile_quark, TRSM )
FUNCTION_QUARK( CORE_dlaswpc_ontile_quark, LASWP )
FUNCTION_QUARK( CORE_dlatro_quark, LATRO )
FUNCTION_QUARK( CORE_dlatro_f1_quark, LATRO )
FUNCTION_QUARK( CORE_dlauum_quark, LAUUM )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_dplgsy_quark, PLGHE )
#endif
FUNCTION_QUARK( CORE_dplgsy_quark, PLGSY )
FUNCTION_QUARK( CORE_dplrnt_quark, PLRNT )
FUNCTION_QUARK( CORE_dplssq_quark, LASSQ )
FUNCTION_QUARK( CORE_dpltmg_quark, PLRNT )
FUNCTION_QUARK( CORE_dpltmg_chebvand_quark, PLRNT )
FUNCTION_QUARK( CORE_dpltmg_circul_quark, PLRNT )
FUNCTION_QUARK( CORE_dpltmg_fiedler_quark, PLRNT )
FUNCTION_QUARK( CORE_dpltmg_hankel_quark, PLRNT )
FUNCTION_QUARK( CORE_dpltmg_toeppd1_quark, PLRNT )
FUNCTION_QUARK( CORE_dpltmg_toeppd2_quark, PLRNT )
FUNCTION_QUARK( CORE_dpotrf_quark, POTRF )
FUNCTION_QUARK( CORE_dsetvar_quark, SETVAR )
FUNCTION_QUARK( CORE_dshiftw_quark, SHIFTW )
FUNCTION_QUARK( CORE_dshift_quark, SHIFT )
FUNCTION_QUARK( CORE_dssssm_quark, SSSSM )
FUNCTION_QUARK( CORE_dswpab_quark, SWPAB )
FUNCTION_QUARK( CORE_dsymm_quark, SYMM )
FUNCTION_QUARK( CORE_dsyr2k_quark, SYR2K )
FUNCTION_QUARK( CORE_dsyrk_quark, SYRK )
FUNCTION_QUARK( CORE_dsyssq_quark, LASSQ )
FUNCTION_QUARK( CORE_dsyssq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_dtrasm_quark, ASUM )
FUNCTION_QUARK( CORE_dtrasm_f1_quark, ASUM )
FUNCTION_QUARK( CORE_dtrdalg1_quark, TRDALG )
FUNCTION_QUARK( CORE_dtrmm_quark, TRMM )
FUNCTION_QUARK( CORE_dtrmm_p2_quark, TRMM )
FUNCTION_QUARK( CORE_dtrsm_quark, TRSM )
FUNCTION_QUARK( CORE_dtrssq_quark, LASSQ )
FUNCTION_QUARK( CORE_dtrssq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_dtrtri_quark, TRTRI )
FUNCTION_QUARK( CORE_dtslqt_quark, TSLQT )
FUNCTION_QUARK( CORE_dtsmlq_quark, TSMLQ )
FUNCTION_QUARK( CORE_dtsmlq_corner_quark, TSMLQ )
FUNCTION_QUARK( CORE_dtsmlq_sytra1_quark, TSMLQ )
FUNCTION_QUARK( CORE_dtsmqr_quark, TSMQR )
FUNCTION_QUARK( CORE_dtsmqr_corner_quark, TSMQR )
FUNCTION_QUARK( CORE_dtsmqr_sytra1_quark, TSMQR )
FUNCTION_QUARK( CORE_dtsqrt_quark, TSQRT )
FUNCTION_QUARK( CORE_dtstrf_quark, TSTRF )
FUNCTION_QUARK( CORE_dttlqt_quark, TTLQT )
FUNCTION_QUARK( CORE_dttmlq_quark, TTMLQ )
FUNCTION_QUARK( CORE_dttmqr_quark, TTMQR )
FUNCTION_QUARK( CORE_dttqrt_quark, TTQRT )
FUNCTION_QUARK( CORE_dormlq_quark, UNMLQ )
FUNCTION_QUARK( CORE_dormqr_quark, UNMQR )

