/**
 *
 * @file qwrapper_s.c
 *
 *  PLASMA core_blas tracing kernel
 *  PLASMA is a software package provided by Univ. of Tennessee,
 *  Univ. of California Berkeley and Univ. of Colorado Denver
 *
 *  This file provides the wrapper for each function of the
 *  core_blas library which will generate an event before and
 *  after the execution of the kernel.
 *  This file is automatically generated with convert2eztrace.pl
 *  script. DO NOT MANUALLY EDIT THIS FILE.
 *
 * @version 2.6.0
 * @author Mathieu Faverge
 * @date 2010-11-15
 * @generated s Tue Jan  7 11:45:26 2014
 *
 **/
#include <eztrace.h>
#include <ev_codes.h>
#include "common.h"
#include "coreblas_ev_codes.h"
#include "coreblas_macros.h"
#undef COMPLEX
#define REAL
FUNCTION_QUARK( CORE_sasum_quark, ASUM )
FUNCTION_QUARK( CORE_sasum_f1_quark, ASUM )
FUNCTION_QUARK( CORE_sbrdalg1_quark, BRDALG )
FUNCTION_QUARK( CORE_sgeadd_quark, GEADD )
FUNCTION_QUARK( CORE_sgelqt_quark, GELQT )
FUNCTION_QUARK( CORE_sgemm_quark, GEMM )
FUNCTION_QUARK( CORE_sgemm_f2_quark, GEMM )
FUNCTION_QUARK( CORE_sgemm_p2_quark, GEMM )
FUNCTION_QUARK( CORE_sgemm_p3_quark, GEMM )
FUNCTION_QUARK( CORE_sgemm_p2f1_quark, GEMM )
FUNCTION_QUARK( CORE_sgemm_tile_quark, GEMM )
FUNCTION_QUARK( CORE_sgemv_quark, GEMV )
FUNCTION_QUARK( CORE_sgemv_tile_quark, GEMV )
FUNCTION_QUARK( CORE_sgeqp3_init_quark, GEQP3_INIT )
FUNCTION_QUARK( CORE_sgeqp3_larfg_quark, LARFG )
FUNCTION_QUARK( CORE_sgeqp3_norms_quark, GEQP3_NORMS )
FUNCTION_QUARK( CORE_sgeqp3_pivot_quark, GEQP3_PIVOT )
FUNCTION_QUARK( CORE_sgeqp3_tntpiv_quark, GEQRT )
FUNCTION_QUARK( CORE_sgeqp3_update_quark, GEQP3_UPDATE )
FUNCTION_QUARK( CORE_sgeqrt_quark, GEQRT )
FUNCTION_QUARK( CORE_sgessm_quark, GESSM )
FUNCTION_QUARK( CORE_sgessq_quark, LASSQ )
FUNCTION_QUARK( CORE_sgessq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_sgetrf_quark, GETRF )
FUNCTION_QUARK( CORE_sgetrf_incpiv_quark, GETRF )
FUNCTION_QUARK( CORE_sgetrf_nopiv_quark, GETRF )
FUNCTION_QUARK( CORE_sgetrf_reclap_quark, GETRF )
FUNCTION_QUARK( CORE_sgetrf_rectil_quark, GETRF )
FUNCTION_QUARK( CORE_sgetrip_quark, GETRIP )
FUNCTION_QUARK( CORE_sgetrip_f1_quark, GETRIP )
FUNCTION_QUARK( CORE_sgetrip_f2_quark, GETRIP )
FUNCTION_QUARK( CORE_ssygst_quark, HEGST )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_ssymm_quark, HEMM )
#endif
#ifdef COMPLEX
FUNCTION_QUARK( CORE_ssyr2k_quark, HER2K )
#endif
FUNCTION_QUARK( CORE_ssyrfb_quark, HERFB )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_ssyrk_quark, HERK )
#endif
#ifdef COMPLEX
FUNCTION_QUARK( CORE_shessq_quark, LASSQ )
FUNCTION_QUARK( CORE_shessq_f1_quark, LASSQ )
#endif
FUNCTION_QUARK( CORE_slacpy_quark, LACPY )
FUNCTION_QUARK( CORE_slacpy_f1_quark, LACPY )
FUNCTION_QUARK( CORE_slacpy_pivot_quark, LACPY )
FUNCTION_QUARK( CORE_slange_quark, LANGE )
FUNCTION_QUARK( CORE_slange_f1_quark, LANGE )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_slansy_quark, LANHE )
FUNCTION_QUARK( CORE_slansy_f1_quark, LANHE )
#endif
FUNCTION_QUARK( CORE_slansy_quark, LANSY )
FUNCTION_QUARK( CORE_slansy_f1_quark, LANSY )
FUNCTION_QUARK( CORE_slantr_quark, LANGE )
FUNCTION_QUARK( CORE_slantr_f1_quark, LANGE )
FUNCTION_QUARK( CORE_slaset2_quark, LASET )
FUNCTION_QUARK( CORE_slaset_quark, LASET )
FUNCTION_QUARK( CORE_slaswp_quark, LASWP )
FUNCTION_QUARK( CORE_slaswp_f2_quark, LASWP )
FUNCTION_QUARK( CORE_slaswp_ontile_quark, LASWP )
FUNCTION_QUARK( CORE_slaswp_ontile_f2_quark, LASWP )
FUNCTION_QUARK( CORE_sswptr_ontile_quark, TRSM )
FUNCTION_QUARK( CORE_slaswpc_ontile_quark, LASWP )
FUNCTION_QUARK( CORE_slatro_quark, LATRO )
FUNCTION_QUARK( CORE_slatro_f1_quark, LATRO )
FUNCTION_QUARK( CORE_slauum_quark, LAUUM )
#ifdef COMPLEX
FUNCTION_QUARK( CORE_splgsy_quark, PLGHE )
#endif
FUNCTION_QUARK( CORE_splgsy_quark, PLGSY )
FUNCTION_QUARK( CORE_splrnt_quark, PLRNT )
FUNCTION_QUARK( CORE_splssq_quark, LASSQ )
FUNCTION_QUARK( CORE_spltmg_quark, PLRNT )
FUNCTION_QUARK( CORE_spltmg_chebvand_quark, PLRNT )
FUNCTION_QUARK( CORE_spltmg_circul_quark, PLRNT )
FUNCTION_QUARK( CORE_spltmg_fiedler_quark, PLRNT )
FUNCTION_QUARK( CORE_spltmg_hankel_quark, PLRNT )
FUNCTION_QUARK( CORE_spltmg_toeppd1_quark, PLRNT )
FUNCTION_QUARK( CORE_spltmg_toeppd2_quark, PLRNT )
FUNCTION_QUARK( CORE_spotrf_quark, POTRF )
FUNCTION_QUARK( CORE_ssetvar_quark, SETVAR )
FUNCTION_QUARK( CORE_sshiftw_quark, SHIFTW )
FUNCTION_QUARK( CORE_sshift_quark, SHIFT )
FUNCTION_QUARK( CORE_sssssm_quark, SSSSM )
FUNCTION_QUARK( CORE_sswpab_quark, SWPAB )
FUNCTION_QUARK( CORE_ssymm_quark, SYMM )
FUNCTION_QUARK( CORE_ssyr2k_quark, SYR2K )
FUNCTION_QUARK( CORE_ssyrk_quark, SYRK )
FUNCTION_QUARK( CORE_ssyssq_quark, LASSQ )
FUNCTION_QUARK( CORE_ssyssq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_strasm_quark, ASUM )
FUNCTION_QUARK( CORE_strasm_f1_quark, ASUM )
FUNCTION_QUARK( CORE_strdalg1_quark, TRDALG )
FUNCTION_QUARK( CORE_strmm_quark, TRMM )
FUNCTION_QUARK( CORE_strmm_p2_quark, TRMM )
FUNCTION_QUARK( CORE_strsm_quark, TRSM )
FUNCTION_QUARK( CORE_strssq_quark, LASSQ )
FUNCTION_QUARK( CORE_strssq_f1_quark, LASSQ )
FUNCTION_QUARK( CORE_strtri_quark, TRTRI )
FUNCTION_QUARK( CORE_stslqt_quark, TSLQT )
FUNCTION_QUARK( CORE_stsmlq_quark, TSMLQ )
FUNCTION_QUARK( CORE_stsmlq_corner_quark, TSMLQ )
FUNCTION_QUARK( CORE_stsmlq_sytra1_quark, TSMLQ )
FUNCTION_QUARK( CORE_stsmqr_quark, TSMQR )
FUNCTION_QUARK( CORE_stsmqr_corner_quark, TSMQR )
FUNCTION_QUARK( CORE_stsmqr_sytra1_quark, TSMQR )
FUNCTION_QUARK( CORE_stsqrt_quark, TSQRT )
FUNCTION_QUARK( CORE_ststrf_quark, TSTRF )
FUNCTION_QUARK( CORE_sttlqt_quark, TTLQT )
FUNCTION_QUARK( CORE_sttmlq_quark, TTMLQ )
FUNCTION_QUARK( CORE_sttmqr_quark, TTMQR )
FUNCTION_QUARK( CORE_sttqrt_quark, TTQRT )
FUNCTION_QUARK( CORE_sormlq_quark, UNMLQ )
FUNCTION_QUARK( CORE_sormqr_quark, UNMQR )

